### ISSUE TITLE
use of 'consul lock'

### ISSUE THREAD

**Issue by blalor** [hashicorp/consul-replicate#11]
The addition of the `lock` subcommand is interesting, but I'm puzzled by its use here.  If I'm reading the documentation on `consul lock` correctly, If the lock is held on node A and then acquired on node B, `consul-replicate` will be terminated on node A but will not be restarted.  So in order to ensure that it's always running it'll have to be supervised externally.  That seems like unnecessary overhead when `consul-replicate` could just gracefully handle loss and acquisition of locks.

**Comment by armon** [comment]
consul-replicate should always be run under some supervisor anyways (upstart, systemd, etc), so really the difference is now instead of the logic being inside consul-replicate, it is cleanly layered.

**Comment by blalor** [comment]
What was the reasoning behind that? I'm writing some tools that use leader election in a similar fashion and have gone the route of making the service itself reliable so that external supervision isn't required. I'm curious about the design decision. Simplicity?

**Comment by armon** [comment]
@blalor Yep exactly! There was previously a lot of logic outside of the core replication to just setup registrations, handle leader elections, etc when that is more generically handled by "consul lock". It simplifies the code base and lets it focus on a much simpler problem.

**Comment by blalor** [comment]
Thanks, Armon.

**Comment by deepakagarwalgithub** [comment]
What is the CLI for consul-replicate from dc-one to dc-two below?
Is there anything missing?

dc-one (physical datacenter-1)
consul-server-2 : dc:dc-one consul IP:192.168.0.153 client-ip:192.168.0.155

http://192.168.0.155:8500/v1/kv/?recurse=

[{"CreateIndex":1287,"ModifyIndex":1287,"LockIndex":0,"Key":"foo","Flags":0,"Value":"YmFy"},{"CreateIndex":1553,"ModifyIndex":1567,"LockIndex":0,"Key":"service/consul-replicate/statuses/4b6a8b56271d06bed31bfa838eb2235e","Flags":0,"Value":"ewogICJMYXN0UmVwbGljYXRlZCI6IDE1NTIsCiAgIlNvdXJjZSI6ICJ3ZWIiLAogICJEZXN0aW5hdGlvbiI6ICJ3ZWIiCn0="},{"CreateIndex":50,"ModifyIndex":1551,"LockIndex":0,"Key":"web/key1","Flags":0,"Value":"bmV3dmFs"},{"CreateIndex":51,"ModifyIndex":1552,"LockIndex":0,"Key":"web/key2","Flags":0,"Value":"bmV3dmFs"}]

dc-two (physical datacenter-2)
consul-server-4: dc: dc-two consul IP : 192.168.0.158 client-ip:localhost

@consul-server-4:~$ consul-replicate -consul=192.168.0.155:8500
<This call is blocking>

@consul-server-4:~$ curl http://localhost:8500/v1/kv/?recurse
<No keys gets replicated>
@consul-server-4:~$
