### ISSUE TITLE
consul lock on supervisor such as upstart

### ISSUE THREAD

**Issue by cleung2010** [hashicorp/consul-replicate#13]
I am trying to run consul-replicate on all server nodes for a datacenter. However, I keep getting these warnings:

```
2015/03/31 14:45:32 [WARN] serf: received old event consul:new-leader from time 21 (current: 715)
2015/03/31 14:45:46 [WARN] serf: received old event consul:new-leader from time 21 (current: 715)
2015/03/31 14:46:02 [WARN] serf: received old event consul:new-leader from time 21 (current: 715)
```

Additionally since I am running consul-replicate under `consul lock` on an upstart script, I end up not getting any logs for consul-replicate under `/var/log/upstart/`. How can I get around that and get logs?

```
script
...
    exec consul lock -token <token> locks/replicate consul-replicate -config /etc/consul_replicate
end script
```

**Comment by armon** [comment]
@cleung2010 Those warning are probably ignorable. They shouldn't affect this usage, although they are strange. It means very old messages are somehow still being circulated in the cluster. I'd be concerned only if they persist for a long time.

With the logs issue, I'm not an upstart expert but I don't think it logs by default. I think there is probably some additional configuration required, or just redirect the logs to a sink with `> /var/log/upstart/consul-replicate.log`

**Comment by cleung2010** [comment]
@armon thanks for clearing up those warnings, I'll keep an eye and see if they persist. 

Upstart is supposed to log output to `/var/log/upstart/${job}.log` [1] and automatically take care of file rotation. We got a consul service running via upstart, and the logs and log rotation is handled automatically. The thing is that exec in this case is technically executing a consul command, so there is no `consul-replicate.log`. I'll try to redirect the output to `/var/log/upstart/consul-replicate.log` but not sure how I would handle rotation on it.

[1] https://wiki.ubuntu.com/PrecisePangolin/ReleaseNotes/TechnicalOverviewUpstart

**Comment by sethvargo** [comment]
Hi @cleung2010 

I am going to close this out as it seems like it has been fixed. If that is not the case, please let me know and we can revisit it.

**Comment by cleung2010** [comment]
Yep, thanks!

**Comment by chnrxn** [comment]
I'm seeing these "serf: received old event consul:new-leader ..." messages too.

What is the best way to clear these old messages?
