### ISSUE TITLE
Are there any plans to merge this tool with Consul itself?

### ISSUE THREAD

**Issue by c4milo** [hashicorp/consul-replicate#16]

**Comment by sethvargo** [comment]
Hi @c4milo 

Right now, all the Consul tooling is separate (Consul Replicate, EnvConsul, Consul Template, etc). There are plans to package these tools with Consul in the future, but it is unlikely we will _merge_ them. 

This tool, for example, does not require you have Consul installed on your local machine to operate, so we do not want to _require_ Consul as a dependency when most of these tools use the HTTP APIs. As such, the tools will always be distributed independently, but they may be included in Consul core in the future as some additional support helpers.

Does that make sense?

**Comment by c4milo** [comment]
@sethvargo that makes sense too sir. Thanks.
