### ISSUE TITLE
Add Homebrew support. 

### ISSUE THREAD

**Issue by c4milo** [hashicorp/consul-replicate#17]
I see consul y consul-template in Hombrew. It will be cool to have consul-replicate too.

**Comment by sethvargo** [comment]
Hi @c4milo 

Thank you for opening an issue. We do not maintain the official homebrew packages. It looks like homebrew is a community-driven project. If you or a member of the community would like to add them, that would be great. However, we general stay out of the packaging game so we can focus on development :smile: 

Please let me know if you have any questions.

**Comment by c4milo** [comment]
fair enough! thanks.
