### ISSUE TITLE
consul-replicate is not holding up when ran through consul lock

### ISSUE THREAD

**Issue by c4milo** [hashicorp/consul-replicate#18]
Any idea of what I'm doing wrong here?
![](https://cldup.com/hzKIr8lx_y.png)

**Comment by c4milo** [comment]
is that happening because the lock is being held by another process?

**Comment by c4milo** [comment]
if I run it like this it works fine: 

```consul lock -verbose locks/replicate /usr/local/bin/consul-replicate . -ssl -ssl-verify -syslog -log-level=debug -prefix=@us-east-1a```

**Comment by c4milo** [comment]
I finally understand this issue, this is happening because `consul-replicate` is deleting the lock when the prefix is set to the root.

![](https://cldup.com/VX1dTkJejb.png)

**Comment by armon** [comment]
Seems like this is resolved!
