### ISSUE TITLE
It would be useful if consul-replicate waits for a leader to be elected before doing its thing

### ISSUE THREAD

**Issue by c4milo** [hashicorp/consul-replicate#19]
Does it sound like a reasonable thing to do? perhaps exposed through a flag?

**Comment by c4milo** [comment]
This is especially more useful when bootstrapping Consul clusters, with replication, automatically.

**Comment by sethvargo** [comment]
@ryanuber @armon does `consul lock` wait for a leader?

**Comment by c4milo** [comment]
@sethvargo it doesn't look like it does: https://github.com/hashicorp/consul/blob/master/command/lock.go

**Comment by sethvargo** [comment]
Okay. I do not think it makes sense for Consul Replicate to handle the leader election process, but I will wait for @armon or @ryanuber to chime in.

**Comment by ryanuber** [comment]
I can see how this might be difficult to orchestrate if you are waiting for multiple servers to boot. It's possible that we could handle this, but there might be an easier way. @c4milo if you are using something like upstart, you can probably safely have the daemon just try to restart every so often until it successfully starts. This is a problem across all of the Consul tooling, but I think we should defer to a process manager where possible to avoid handling this complexity internally.

**Comment by c4milo** [comment]
I agree, this is what I ended up doing: 

```
description "Consul K/V replication"

start on started consul
stop on stopped consul

respawn

script
	while :; do
		logger -t "consul-replicate" "Waiting for a Consul leader..."
		 elected=`curl http://localhost:8500/v1/status/leader \
			| grep -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' 2>&1 >> /dev/null \
			&& echo "yes!"`

		[ "${elected}" = "yes!" ] && break
		sleep 5
	done

	if [ -f "/etc/service/consul-replicate" ]; then
		. /etc/service/consul-replicate
	fi

	export GOMAXPROCS=1

	logger -t "consul-replicate" "Attempting to start service..."
	exec consul lock -verbose locks/replicate /usr/local/bin/consul-replicate \
		${CONSUL_REPLICATE_FLAGS} \
	>>/var/log/consul-replicate.log 2>&1
end script

post-start exec logger -t "consul-replicate" "Service started."

```

**Comment by sethvargo** [comment]
Sounds like this is resolved!
