### ISSUE TITLE
consul-replicate doesn't attempt HTTPS connections when SSL flag specified

### ISSUE THREAD

**Issue by roycrowder** [hashicorp/consul-replicate#21]
Attempting to replicate and my Consul servers require SSL. I have redacted certain information like datacenter and hostnames so please ignore dc1 and server.com.

Based on the GET log lines, it's using HTTP instead of HTTPS even though I have specified the SSL flag.

[root replicate]# consul-replicate -consul="server.com:8543" -ssl -ssl-verify -prefix="vault@dc1" -once -log-level=debug
2015/06/04 18:52:50 [INFO] (runner) creating new runner (once: true)
2015/06/04 18:52:50 [INFO] (runner) creating consul/api client
2015/06/04 18:52:50 [DEBUG] (runner) setting address to server.com:8543
2015/06/04 18:52:50 [DEBUG] (runner) setting basic auth
2015/06/04 18:52:50 [INFO] (runner) creating Watcher
2015/06/04 18:52:50 [INFO] (runner) starting
2015/06/04 18:52:50 [INFO] (watcher) adding "storeKeyPrefix(vault@dc1)"
2015/06/04 18:52:50 [DEBUG] (watcher) "storeKeyPrefix(vault@dc1)" starting
2015/06/04 18:52:50 [DEBUG] (view) "storeKeyPrefix(vault@dc1)" starting fetch
2015/06/04 18:52:50 [DEBUG] ("storeKeyPrefix(vault@dc1)") querying Consul with &{Datacenter:dc1 AllowStale:false RequireConsistent:false WaitIndex:0 WaitTime:1m0s Token:}
2015/06/04 18:52:50 [ERR] (view) "storeKeyPrefix(vault@dc1)" Get http://server.com:8543/v1/kv/vault?dc=dc1&recurse=&wait=60000ms: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
2015/06/04 18:52:50 [INFO] (view) "storeKeyPrefix(vault@dc1)" errored, retrying in 5s
2015/06/04 18:52:50 [ERR] (runner) watcher reported error: Get http://server.com:8543/v1/kv/vault?dc=dc1&recurse=&wait=60000ms: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
2015/06/04 18:52:50 [INFO] (runner) running

**Comment by roycrowder** [comment]
FYI

consul-replicate -version
consul-replicate v0.2.0

**Comment by deepakagarwalgithub** [comment]
What is the CLI for consul-replicate from dc-one to dc-two below?
Is there anything missing?

dc-one (physical datacenter-1)
consul-server-2 : dc:dc-one consul IP:192.168.0.153 client-ip:192.168.0.155

http://192.168.0.155:8500/v1/kv/?recurse=

[{"CreateIndex":1287,"ModifyIndex":1287,"LockIndex":0,"Key":"foo","Flags":0,"Value":"YmFy"},{"CreateIndex":1553,"ModifyIndex":1567,"LockIndex":0,"Key":"service/consul-replicate/statuses/4b6a8b56271d06bed31bfa838eb2235e","Flags":0,"Value":"ewogICJMYXN0UmVwbGljYXRlZCI6IDE1NTIsCiAgIlNvdXJjZSI6ICJ3ZWIiLAogICJEZXN0aW5hdGlvbiI6ICJ3ZWIiCn0="},{"CreateIndex":50,"ModifyIndex":1551,"LockIndex":0,"Key":"web/key1","Flags":0,"Value":"bmV3dmFs"},{"CreateIndex":51,"ModifyIndex":1552,"LockIndex":0,"Key":"web/key2","Flags":0,"Value":"bmV3dmFs"}]

dc-two (physical datacenter-2)
consul-server-4: dc: dc-two consul IP : 192.168.0.158 client-ip:localhost

@consul-server-4:~$ consul-replicate -consul=192.168.0.155:8500
<This call is blocking>

@consul-server-4:~$ curl http://localhost:8500/v1/kv/?recurse
<No keys gets replicated>
@consul-server-4:~$

**Comment by justintime** [comment]
@roycrowder not to hijack your issue, but it looks like you're trying to use consul-replicate on vault data.  Are you having any success?  If so, care to share what you did to make it work over in https://github.com/hashicorp/vault/issues/674?

**Comment by abhimanyuvarma** [comment]
Any update on this issue - i am facing the same problem ?
