### ISSUE TITLE
consul replicate not replicating keys

### ISSUE THREAD

**Issue by deepakagarwalgithub** [hashicorp/consul-replicate#24]
What is the CLI for consul-replicate from dc-one to dc-two below?
Is there anything missing?

dc-one (physical datacenter-1)
consul-server-2 : dc:dc-one consul IP:192.168.0.153 client-ip:192.168.0.155

http://192.168.0.155:8500/v1/kv/?recurse=

[{"CreateIndex":1287,"ModifyIndex":1287,"LockIndex":0,"Key":"foo","Flags":0,"Value":"YmFy"},{"CreateIndex":1553,"ModifyIndex":1567,"LockIndex":0,"Key":"service/consul-replicate/statuses/4b6a8b56271d06bed31bfa838eb2235e","Flags":0,"Value":"ewogICJMYXN0UmVwbGljYXRlZCI6IDE1NTIsCiAgIlNvdXJjZSI6ICJ3ZWIiLAogICJEZXN0aW5hdGlvbiI6ICJ3ZWIiCn0="},{"CreateIndex":50,"ModifyIndex":1551,"LockIndex":0,"Key":"web/key1","Flags":0,"Value":"bmV3dmFs"},{"CreateIndex":51,"ModifyIndex":1552,"LockIndex":0,"Key":"web/key2","Flags":0,"Value":"bmV3dmFs"}]

dc-two (physical datacenter-2)
consul-server-4: dc: dc-two consul IP : 192.168.0.158 client-ip:localhost

@consul-server-4:~$ consul-replicate -consul=192.168.0.155:8500
<This call is blocking>

@consul-server-4:~$ curl http://localhost:8500/v1/kv/?recurse
<No keys gets replicated>
@consul-server-4:~$

**Comment by sethvargo** [comment]
Hi @deepakagarwalgithub 

All usage information can be found in the README: https://github.com/hashicorp/consul-replicate#command-line

**Comment by deepakagarwalgithub** [comment]
I used the CLI as mentioned in README.

It gave below error, am I missing anything here ?

@consul-server-4:~$ consul-replicate -consul=192.168.0.155:8500 -prefix web@dc-one
Consul Replicate returned errors:
1 error(s) occurred:

* local datacenter cannot be the source datacenter
@consul-server-4:~$

**Comment by deepakagarwalgithub** [comment]
I have 2 datacenter dc-one and dc-two with separate consul cluster on each dc, over same subnet.

Is there anything I need to change in dc configuration?

dc-one : 

@consul-server-3:~$ consul members -detailed
Node             Address             Status   Tags
consul-server-3  192.168.0.157:8301  alive    vsn=2,vsn_min=1,vsn_max=2,build=0.5.1:dc6795a5,port=8300,expect=3,role=consul,dc=dc-one
consul-server-2  192.168.0.153:8301  leaving  role=consul,dc=dc-one,vsn=2,vsn_min=1,vsn_max=2,build=0.5.2:9a9cc934,port=8300,expect=3
consul-client-1  192.168.0.154:8301  alive    role=node,dc=dc-one,vsn=2,vsn_min=1,vsn_max=2,build=0.5.1:dc6795a5
consul-server-1  192.168.0.152:8301  alive    dc=dc-one,vsn=2,vsn_min=1,vsn_max=2,build=0.5.1:dc6795a5,port=8300,expect=3,role=consul
@consul-server-3:~$

dc-two

@consul-server-4:~$ consul members -detailed
Node             Address             Status  Tags
consul-server-4  192.168.0.158:8301  alive   vsn_max=2,build=0.5.1:dc6795a5,port=8300,bootstrap=1,role=consul,dc=dc-two,vsn=2,vsn_min=1

**Comment by sethvargo** [comment]
Hi @deepakagarwalgithub 

You need to run Consul Replicate from one of the slaves in the other datacenter. You run consul-replicate from the agent you WANT to replicate INTO, not the one you want to replicate from.

Additionally, master-master replication is not supported.

**Comment by deepakagarwalgithub** [comment]
Now consul-replicate is executed ON dc-two client-2 to replicate FROM dc-one client-1 (client-ip 192.168.0.156)

Still I get the same error, please suggest what could be missing here ?

Is the below consul-replicate cli correct?
@consul-client-2:~$  consul-replicate -consul=192.168.0.156:8500 -prefix=web@dc-one

dc-one client-1 
cluster-ip 192.168.0.154 client-ip 192.168.0.156

dc-two  client-2 
cluster-ip 192.168.0.159 client-ip 192.168.0.160


dc-one

@consul-client-1:~$ consul members -rpc-addr=192.168.0.156:8400 -detailed
Node             Address             Status  Tags
consul-client-1  192.168.0.154:8301  alive   build=0.5.1:dc6795a5,role=node,dc=dc-one,vsn=2,vsn_min=1,vsn_max=2
consul-server-1  192.168.0.152:8301  alive   expect=3,role=consul,dc=dc-one,vsn=2,vsn_min=1,vsn_max=2,build=0.5.1:dc6795a5,port=8300
consul-server-3  192.168.0.157:8301  alive   vsn=2,vsn_min=1,vsn_max=2,build=0.5.1:dc6795a5,port=8300,expect=3,role=consul,dc=dc-one
consul-server-2  192.168.0.153:8301  alive   vsn_min=1,vsn_max=2,build=0.5.2:9a9cc934,port=8300,expect=3,role=consul,dc=dc-one,vsn=2


sfuser@consul-client-1:~$ curl http://192.168.0.156:8500/v1/kv/?recurse
[{"CreateIndex":1287,"ModifyIndex":1287,"LockIndex":0,"Key":"foo","Flags":0,"Value":"YmFy"},{"CreateIndex":1553,"ModifyIndex":1870,"LockIndex":0,"Key":"service/consul-replicate/statuses/4b6a8b56271d06bed31bfa838eb2235e","Flags":0,"Value":"ewogICJMYXN0UmVwbGljYXRlZCI6IDE4NjQsCiAgIlNvdXJjZSI6ICJ3ZWIiLAogICJEZXN0aW5hdGlvbiI6ICJ3ZWIiCn0="},{"CreateIndex":50,"ModifyIndex":1551,"LockIndex":0,"Key":"web/key1","Flags":0,"Value":"bmV3dmFs"},{"CreateIndex":51,"ModifyIndex":1552,"LockIndex":0,"Key":"web/key2","Flags":0,"Value":"bmV3dmFs"},{"CreateIndex":1597,"ModifyIndex":1864,"LockIndex":0,"Key":"web/key5","Flags":0,"Value":"bmV3dmFs"}]sfuser@consul-client-1:~$



dc-two

@consul-client-2:~$ consul members -rpc-addr=192.168.0.160:8400 -detailed
Node             Address             Status  Tags
consul-client-2  192.168.0.159:8301  alive   vsn=2,vsn_min=1,vsn_max=2,build=0.5.1:dc6795a5,role=node,dc=dc-two
consul-server-4  192.168.0.158:8301  alive   port=8300,bootstrap=1,role=consul,dc=dc-two,vsn=2,vsn_min=1,vsn_max=2,build=0.5.1:dc6795a5

@consul-client-2:~$  consul-replicate -consul=192.168.0.156:8500 -prefix=web@dc-one
Consul Replicate returned errors:
1 error(s) occurred:

* local datacenter cannot be the source datacenter

**Comment by deepakagarwalgithub** [comment]
Anyone please help what is missing here ?

The DC-DC replicate using clients on either DC is not working as above in last comment.

**Comment by armon** [comment]
@deepakagarwalgithub The problem is you've configured it to replicate from DC1 into DC1 which is not allowed.

You should run it like:

    $ consul-replicate -consul=<AgentInDC2> -prefix=web@dc1

Ideally, the agent in DC2 is on the same machine, so that the default address of 127.0.0.1:8500 works and you do not even need to specify it.

**Comment by deepakagarwalgithub** [comment]
I changed consul-replicate as suggested, now I am getting different error.

Invoking replication from dc2 client-2
192.168.0.154 is client-1 ip of dc1


@consul-client-2:~$ consul-replicate -prefix=web@192.168.0.154
2015/08/18 22:05:30 [ERR] (view) "storeKeyPrefix(web@192.168.0.154)" Unexpected response code: 500
2015/08/18 22:05:30 [ERR] (runner) watcher reported error: Unexpected response code: 500
2015/08/18 22:05:35 [ERR] (view) "storeKeyPrefix(web@192.168.0.154)" Unexpected response code: 500
2015/08/18 22:05:35 [ERR] (runner) watcher reported error: Unexpected response code: 500

@consul-client-2:~$ consul-replicate -prefix=web@dc1
2015/08/18 22:05:39 [ERR] (view) "storeKeyPrefix(web@dc1)" Unexpected response code: 500
2015/08/18 22:05:39 [ERR] (runner) watcher reported error: Unexpected response code: 500

**Comment by armon** [comment]
@deepakagarwalgithub The `-prefix` value is incorrect still. The value after the `@` is the datacenter name, not the IP of the node. The Consul cluster automatically does the multi-datacenter request forwarding. You just need to specify the DC name.

**Comment by deepakagarwalgithub** [comment]
I have datacenter name only.

@consul-client-2:~$ consul-replicate -prefix=web@dc1
2015/08/18 22:05:39 ERR "storeKeyPrefix(web@dc1)" Unexpected response code: 500
2015/08/18 22:05:39 ERR watcher reported error: Unexpected response code: 500

**Comment by deepakagarwalgithub** [comment]
I have tried as suggested, still not working.

consul-client-2 is dc-two client

trying to replicate from dc-one

consul-replicate -prefix=web@dc-one
2015/08/18 22:42:22 [ERR] (view) "storeKeyPrefix(web@dc-one)" Unexpected
response code: 500
2015/08/18 22:42:22 [ERR] (runner) watcher reported error: Unexpected
response code: 500

 2015/08/18 22:42:22 [ERR] http: Request
/v1/kv/web?dc=dc-one&recurse=&wait=60000ms, error: rpc error: No path to
datacenter
    2015/08/18 22:42:27 [ERR] http: Request
/v1/kv/web?dc=dc-one&recurse=&wait=60000ms, error: rpc error: No path to
datacenter


ping from dc-two client-2 to dc-one nodes is fine?
Is there any mapping required for dc-one in dc-two client?


sfuser@consul-docker:~$ ping 192.168.0.152
PING 192.168.0.152 (192.168.0.152) 56(84) bytes of data.
64 bytes from 192.168.0.152: icmp_seq=1 ttl=64 time=0.967 ms
^C
--- 192.168.0.152 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.967/0.967/0.967/0.000 ms
sfuser@consul-docker:~$ ping 192.168.0.153
PING 192.168.0.153 (192.168.0.153) 56(84) bytes of data.
64 bytes from 192.168.0.153: icmp_seq=1 ttl=64 time=0.634 ms
^C
--- 192.168.0.153 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.634/0.634/0.634/0.000 ms
sfuser@consul-docker:~$ ping 192.168.0.154
PING 192.168.0.154 (192.168.0.154) 56(84) bytes of data.
64 bytes from 192.168.0.154: icmp_seq=1 ttl=64 time=0.887 ms
^C
--- 192.168.0.154 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.887/0.887/0.887/0.000 ms
sfuser@consul-docker:~$ ping 192.168.0.157
PING 192.168.0.157 (192.168.0.157) 56(84) bytes of data.
64 bytes from 192.168.0.157: icmp_seq=1 ttl=64 time=1.21 ms
^C
--- 192.168.0.157 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 1.219/1.219/1.219/0.000 ms


@consul-client-1:~$ consul members -detailed
Node             Address             Status  Tags
consul-server-1  192.168.0.152:8301  alive
expect=3,role=consul,dc=dc-one,vsn=2,vsn_min=1,vsn_max=2,build=0.5.1:dc6795a5,port=8300
consul-client-1  192.168.0.154:8301  alive
vsn=2,vsn_min=1,vsn_max=2,build=0.5.1:dc6795a5,role=node,dc=dc-one
consul-server-3  192.168.0.157:8301  alive
build=0.5.1:dc6795a5,port=8300,expect=3,role=consul,dc=dc-one,vsn=2,vsn_min=1,vsn_max=2
consul-server-2  192.168.0.153:8301  alive
vsn_min=1,vsn_max=2,build=0.5.2:9a9cc934,port=8300,expect=3,role=consul,dc=dc-one,vsn=2

**Comment by deepakagarwalgithub** [comment]
I have tried as suggested, still not working.

consul-client-2 is dc-two client

trying to replicate from dc-one

consul-replicate -prefix=web@dc-one
2015/08/18 22:42:22 [ERR] (view) "storeKeyPrefix(web@dc-one)" Unexpected response code: 500
2015/08/18 22:42:22 [ERR] (runner) watcher reported error: Unexpected response code: 500

 2015/08/18 22:42:22 [ERR] http: Request /v1/kv/web?dc=dc-one&recurse=&wait=60000ms, error: rpc error: No path to datacenter
    2015/08/18 22:42:27 [ERR] http: Request /v1/kv/web?dc=dc-one&recurse=&wait=60000ms, error: rpc error: No path to datacenter


ping from dc-two client-2 to dc-one nodes is fine?
Is there any mapping required for dc-one in dc-two client?


sfuser@consul-docker:~$ ping 192.168.0.152
PING 192.168.0.152 (192.168.0.152) 56(84) bytes of data.
64 bytes from 192.168.0.152: icmp_seq=1 ttl=64 time=0.967 ms
^C
--- 192.168.0.152 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.967/0.967/0.967/0.000 ms
sfuser@consul-docker:~$ ping 192.168.0.153
PING 192.168.0.153 (192.168.0.153) 56(84) bytes of data.
64 bytes from 192.168.0.153: icmp_seq=1 ttl=64 time=0.634 ms
^C
--- 192.168.0.153 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.634/0.634/0.634/0.000 ms
sfuser@consul-docker:~$ ping 192.168.0.154
PING 192.168.0.154 (192.168.0.154) 56(84) bytes of data.
64 bytes from 192.168.0.154: icmp_seq=1 ttl=64 time=0.887 ms
^C
--- 192.168.0.154 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.887/0.887/0.887/0.000 ms
sfuser@consul-docker:~$ ping 192.168.0.157
PING 192.168.0.157 (192.168.0.157) 56(84) bytes of data.
64 bytes from 192.168.0.157: icmp_seq=1 ttl=64 time=1.21 ms
^C
--- 192.168.0.157 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 1.219/1.219/1.219/0.000 ms


@consul-client-1:~$ consul members -detailed
Node             Address             Status  Tags
consul-server-1  192.168.0.152:8301  alive   expect=3,role=consul,dc=dc-one,vsn=2,vsn_min=1,vsn_max=2,build=0.5.1:dc6795a5,port=8300
consul-client-1  192.168.0.154:8301  alive   vsn=2,vsn_min=1,vsn_max=2,build=0.5.1:dc6795a5,role=node,dc=dc-one
consul-server-3  192.168.0.157:8301  alive   build=0.5.1:dc6795a5,port=8300,expect=3,role=consul,dc=dc-one,vsn=2,vsn_min=1,vsn_max=2
consul-server-2  192.168.0.153:8301  alive   vsn_min=1,vsn_max=2,build=0.5.2:9a9cc934,port=8300,expect=3,role=consul,dc=dc-one,vsn=2

**Comment by deepakagarwalgithub** [comment]
I don't have any DNS in the setup, is there any consul DNS required?

**Comment by armon** [comment]
The error "No path to datacenter" is indicating that there is no way for requests to go between the datacenters because the servers do not know about each other yet.

Have you setup multi-DC correctly? Can you make normal requests between datacenters? What is the output of `consul members -wan` on the servers?
