### ISSUE TITLE
Any plans to support master-master replication?

### ISSUE THREAD

**Issue by F21** [hashicorp/consul-replicate#28]
Are there any plans to support master-master replication? With the current master-slave setup, if the master dc fails, all writes will be blocked unless we have some fail-over to automatically turn another dc into a master.

**Comment by sethvargo** [comment]
Hi @F21 

There are no plans to support master-master replication. Master-master replication introduces many real-time data race conditions that are impossible to counteract.

**Comment by F21** [comment]
@sethvargo 

I would like to be able to set a key from any data center and watch it from any data center. What's the best way of achieving that without master-master replication?

**Comment by armon** [comment]
@F21 The KV store of each datacenter is fully independent, so you could either do a watch against a key in every datacenter, or you could elect a single DC as the "primary" and watch it there. The recommend strategy is to set one DC as the primary and issue writes there, and use consul-replicate to pull changes from that DC into all other DCs. Then clients can watch the key in the local DC.

**Comment by denzuko** [comment]
@armon So that sounds like manual replication, why not automated that in some fashion?
