### ISSUE TITLE
Support for multiple prefixes

### ISSUE THREAD

**Issue by cleung2010** [hashicorp/consul-replicate#3]
There should be support for providing an array of prefixes instead of a single prefix root.

This would enable a cluster to replicate multiple K/V prefixes that are located under separate root paths.

**Comment by cleung2010** [comment]
@armon Quick question, why is it `case <- leaderCh` on https://github.com/hashicorp/consul-replicate/blob/master/replicate.go#L98? Isn't that saying "Go to ACQUIRE if there is a leader"?

**Comment by armon** [comment]
@cleung2010 The leaderCh is closed when leadership is lost, so that line is saying "if leader ship is lost, try to re-acquire leadership."

**Comment by cleung2010** [comment]
I see, thanks!
