### ISSUE TITLE
Directory-clear if DCs share the same Directory-name

### ISSUE THREAD

**Issue by doertedev** [hashicorp/consul-replicate#30]
Oy.

Our nodes across all datacenters have their keys set in the same directory name. Yet when running consul-replicate, it comes along and clears the existing directory (having data for its datacenter) and replicates the remote datacenter into the same directory (persisting remote datacenter data).

I know this seems like a too-political-question, so I'm proposing:

* check for keys in $directory that are present
* check which ones are in remote $dc
* check if there are overlaps
* if there are none: pull entries & subdirectories in the existing directory without removing existing entries & subdirs.

<3, @doerteDev.

**Comment by sethvargo** [comment]
Hi @doertedev 

Are you performing master-master replication? Master-master replication is not supported.

**Comment by sethvargo** [comment]
Closing due to lack of response. If this is still an occurring, please open a new issue and include the script you are running and the debug output. Thanks!
