### ISSUE TITLE
Containerization

### ISSUE THREAD

**Issue by doertedev** [hashicorp/consul-replicate#31]
Oy.

The docs state that the leader doesn't get elected automatically, and that you need to aquire a lock first:

```
consul lock locks/replicate consul-replicate -prefix ...
```

The problem I'm having is that I'm trying to run the consul server and replicate under two different containers. So the binary of one isn't available in the other. I think I'm missing something here, because right now I have two datacenters with three servers each, on which a consul-server and a consul-replicate container are running, and the consul-replicate containers are basically doing nothing. Neither are lock or service directories pop up in the k/v store. So before digging deeper into this:

Am I to throw consul-replicate into the consul-server container in order to get this to work and have the replicators elect a leader when shooting the first lock-aquiring command by hand?

Thanks in advance.

<3, @doerteDev.

**Comment by sethvargo** [comment]
Hi @doertedev 

Are you trying to perform master-master replication? That [is not supported](https://github.com/hashicorp/consul-replicate#faq).

**Comment by doertedev** [comment]
Yupp, makes sense. Threw the binary on one of the consul containers and its running besides consul, replicates without a flaw. Thanks for clearing that up @sethvargo
