### ISSUE TITLE
Service Replication

### ISSUE THREAD

**Issue by 0x9090** [hashicorp/consul-replicate#33]
Maybe this is a feature request, but I would like to be able to replicate service check data across consul cluster instances. Being able to export the service definition json, and import to a different environment would be valuable.

**Comment by sethvargo** [comment]
Hi @0x9090 

This is not a recommended approach. Services exist per-data center and are registered with the JSON file. If you have a service that runs in multiple data centers, you can share the service JSON using CM or a central repo. Thanks!
