### ISSUE TITLE
Error if log-level declared in config

### ISSUE THREAD

**Issue by cleung2010** [hashicorp/consul-replicate#34]
I am getting the following error when `log-level` is declared in the config file instead of being passed into the commad:
```
Consul Replicate returned errors:
runner: 1 error(s) occurred:

* 1 error(s) decoding:

* '' has invalid keys: log-level
```

`config.json`:
```
{
  "consul": "127.0.0.1:8500",
  "log-level": "info",
  "prefix": [
    {
      "source": "global@default"
    }
  ]
}
```

**Comment by slackpad** [comment]
Hi @cleung2010 that should be `log_level` for the config version - does that work for you?

**Comment by cleung2010** [comment]
Thanks, I'll try that out. https://github.com/hashicorp/consul-replicate#options should include the mappings for config file options :)

**Comment by cleung2010** [comment]
It's running without errors now.

**Comment by slackpad** [comment]
I added an example for `log_level` - https://github.com/hashicorp/consul-replicate/commit/ec5d4e0e14235089624f9fc638279cff884fe93c.
