### ISSUE TITLE
Use consult-replicate in non-WAN multicluster environments

### ISSUE THREAD

**Issue by asador** [hashicorp/consul-replicate#45]
We would like to use Consul in our different data centers as KV store, and use one cluster as the primary to read and write data KV data and replicate the data to all other clusters. Our network configuration does not allow communication between some data centers so we cannot setup WAN among all clusters. Would that be possible to enhance consult-replicate to support kv replication from one cluster to another regardless of being part of a WAN pool?

**Comment by sethvargo** [comment]
Hi @asador 

Master-master replication is not something we have planned for consul-replicate. This is discussed in the README. However, Consul's API client libraries are open source, so you could build this yourself if that was a use case. Thanks!
