### ISSUE TITLE
Syslog and log level not honored via config file setting

### ISSUE THREAD

**Issue by ssenaria** [hashicorp/consul-replicate#46]
Running the following yields no output to syslog or the console. However, the keys are synced correctly, I just don't see any logs.
 
    ./consul-replicate -config=/opt/consul-replicate/config.json

If I pass the parameters via the CLI, I get the intended results. I see output to console and it logs into a log file.

    ./consul-replicate -config=/opt/consul-replicate/config.json -syslog -log-level=debug

**config.json**

    consul = "127.0.0.1:8500"
    retry = "10s"
    log_level = "debug"

    syslog {
    enabled = true
    facility = "LOCAL1"
    }

    prefix {
      source = "apichecks@phl"
    }

    prefix {
      source = "deploylist@phl"
    }

**Comment by sethvargo** [comment]
Hi @ssenaria 

I think this is something that has been fixed on master, but we have not yet released. I just tried and it looks like it's working, but can you try compiling from master to make sure?

**Comment by ssenaria** [comment]
Oh, ok. I was having issues compiling it and ended up using the release binary from Feb. I'll have to open another ticket then since I'm not too familiar with compiling go binaries.

**Comment by ssenaria** [comment]
Works using code from `master`
