### ISSUE TITLE
Not able to compile into binary

### ISSUE THREAD

**Issue by ssenaria** [hashicorp/consul-replicate#47]
Go 1.6.2

    GOPATH=/home/ssen/work
    GOROOT=/home/ssen/bin/go
    CONSUL-REPLICATE=/home/ssen/work/src/consul-replicate

cd /home/ssen/work/src/consul-replicate
make

Then I get a bunch of errors stating it can't find packages from `github.com/hashicorp/<INSERT REPO>`

Snippet:

    ==> Generating...
    can't load package: package consul-replicate: code in directory /home/ssen/work/src/consul-replicate     expects import "github.com/hashicorp/consul-replicate"
    ==> Running tests...
    can't load package: package consul-replicate: code in directory /home/ssen/work/src/consul-replicate     expects import "github.com/hashicorp/consul-replicate"
    import cycle not allowed
    package consul-replicate/vendor/github.com/fatih/structs`

**Comment by sethvargo** [comment]
Hi @ssenaria 

What command did you run after cloning the repo?

You need to clone into `$GOPATH/src/github.com/hashicorp/consul-replicate`

**Comment by ssenaria** [comment]
I changed to the directory `/home/ssen/work/src/consul-replicate` and then ran `make`

So here's what I'm doing. Remember, this is all new to me (Go). Do I need to checkout the other repos? It wasn't clear from the instructions for consul-replicate. I was assuming that i would just change into the folder and run make and the makefile would d/l the dependencies? 

    git clone https://github.com/hashicorp/consul-replicate.git $GOPATH/src/github.com/hashicorp/consul-replicate
    cd $GOPATH/src/github.com/hashicorp/consul-replicate.git
    make

Snippet:

    ==> Generating...
    ==> Running tests...
    config.go:12:2: cannot find package "github.com/hashicorp/consul-template/dependency" in any of:
	/home/ssen/bin/go/src/github.com/hashicorp/consul-template/dependency (from $GOROOT)
	/home/ssen/work/src/github.com/hashicorp/consul-template/dependency (from $GOPATH)
    ...
    ...    
    import cycle not allowed
    package github.com/hashicorp/consul-replicate
	imports bytes
	imports errors
	imports runtime
	imports runtime/internal/atomic
	imports runtime
    make: *** [test] Error 123

**Comment by sethvargo** [comment]
Hi @ssenaria 

I totally understand how Go can be confusing (I've been there). You do not need to checkout the other repos, but Go requires a very specific file structure:

```
$GOPATH/src/$DOMAIN/$NAMESPACE/$NAME
```

So you need to clone the project into:

```
/home/ssen/work/src/github.com/hashicorp/consul-replicate
```

**Comment by ssenaria** [comment]
Yep, that's where it is.

    ssen:inbuild003 {~/work/src/github.com/hashicorp/consul-replicate}-> echo $GOPATH
    /home/ssen/work

    ssen:inbuild003 {~/work/src/github.com/hashicorp/consul-replicate}-> pwd
    /home/ssen/work/src/github.com/hashicorp/consul-replicate

Then run `make` in the folder I cloned into (my PWD at the moment). Is that correct?
