### ISSUE TITLE
Keys are being skipped and deleted when using config option

### ISSUE THREAD

**Issue by ssenaria** [hashicorp/consul-replicate#48]
Using codebase from `master` branch ...

If I run using the config file flag, it skips and/or deletes my keys (i re-sync them using the CLI flags). If I run and pass the flags via the command line it works fine.

Using `config`

    ./consul-replicate -config=/opt/consul-replicate/config.json

Using CLI flags works fine.

    ./consul-replicate -prefix="deploylist@phl" -consul "ocd.atl.ariasystems.net:8500" -syslog -log-level=debug

Also, when running the app using a config flag, the prefix for `apichecks` is coming through incorrectly. The keys should be `apichecks/worldpay/<KEY>`

    2016/06/02 14:42:07 [DEBUG] (runner) skipping because "apichecksworldpay/" is already replicated
    2016/06/02 14:42:07 [DEBUG] (runner) skipping because "apichecksworldpay/api_desc" is already replicated
    2016/06/02 14:42:07 [DEBUG] (runner) skipping because "apichecksworldpay/api_type" is already replicated

My config:

    consul = "127.0.0.1:8500"
    retry = "10s"
    log_level = "debug"
    max_stale = "10m"

    syslog {
        enabled = true
    }

    prefix {
        source = "apichecks@phl"
    }

    prefix {
        source = "deploylist@phl"
    }

**Comment by sethvargo** [comment]
Hi @ssenaria 

Can you try adding a trailing slash to the config file:

```
apichecks/@ph1
```

If that works, I know what the fix is.

**Comment by ssenaria** [comment]
Hello,

That did it. Works now. 

I have a different question. maybe this isn't how it's supposed to work but let's say I deleted a key from my slave server. How can I resync the key? consul-replicate is telling me it's already replicated.

**Comment by sethvargo** [comment]
Hey @ssenaria 

I have updated the deps and fixed the trailing slash issue for the config. Regarding your follow-up question, could you please open a new issue and describe your setup, including the debug output?
