### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by thunderstumpges** [hashicorp/consul-replicate#49]
It looks like 0.2.0 is about a year old now, and there have been many fixes (looking specifically for issue #25, #40, and #41) Is there a new binaries release planned any time soon? Wondering if we can avoid building ourselves from tip.

Thanks!

**Comment by sethvargo** [comment]
Hi @thunderstumpges 

We have a scheduled release cycle - a new release will be available soon.

**Comment by thunderstumpges** [comment]
Thanks @sethvargo. While I appreciate that you do have a release schedule, could you please elaborate just a *little*? What schedule is it? How soon is soon? Am I missing something or was the last release really over a year ago? Thanks in advance.

**Comment by mynameisgv** [comment]
May I please know the next release date.

Thanks
