### ISSUE TITLE
Restarting service results in errors

### ISSUE THREAD

**Issue by justicel** [hashicorp/consul-replicate#5]
If I restart the service and get a new PID the old one doesn't appear to be invalidated, resulting in an error from the 'consul-replicate' service check.

**Comment by armon** [comment]
Can you provide more details? What errors are you getting? If you do not gracefully stop the replicator it has no opportunity to cleanup the old service entry.

**Comment by justicel** [comment]
I'll replicate it and send the errors/screenshots/etc.

Essentially though it's that one of the replicate services dies and once it's restored the previous PID does not get cleaned up and that old PID stays in an error state.

**Comment by armon** [comment]
Ah yeah. This is a known limitation. It cleans up only if killed gracefully.
