### ISSUE TITLE
Consul-replicate unnecessarily uses a shell to spawn its command

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/consul-replicate#50]
consul-replicate requires that the user running it have a valid shell, because it uses said shell to invoke whatever command it's wrapping.  This isn't required, though - exec()ing the command should be sufficient. 

Fixing this would allow us to set the shell of our dedicated consul-replicate user to `/bin/false` and reduce our attack surface.

**Comment by sethvargo** [comment]
Hi @mfischer-zd 

Consul-replicate does not spawn a command or shell. I think this meant to be under envconsul/consul-template, and both of those tools have been updated to no longer require a shell. A valid shell is required to _build_ CR, but you do not need one to run the compiled binary.

**Comment by mfischer-zd** [comment]
You're right!  I misplaced this bug.  Thanks.
