### ISSUE TITLE
Skipping keys because the key is already replicated?

### ISSUE THREAD

**Issue by ssenaria** [hashicorp/consul-replicate#52]
I have two clusters in two different DCs running v0.2

Primary -> PHL (3 nodes)
Secondary -> ATL (3 nodes)

I'm running consul-replicate on a client in ATL. 

`./consul-replicate -config=/opt/consul-replicate/config.json`

    consul = "ocd.atl.ariasystems.net:8500"
    retry = "10s"
    log_level = "debug"
    max_stale = "10m"

    syslog {
       enabled = true
    }

    prefix {
        source = "apichecks/@phl"
    }

    prefix {
        source = "deploylist/@phl"
    }

If I delete a key on the ATL side and run `consul-replicate` again, it tells me the key is already replicated.

    consul-replicate[21216]: (runner) skipping because "apichecks/worldpay/url" is already replicated

**Comment by slackpad** [comment]
Hi @ssenaria consul-replicate stores state about what it has already replicated:

> status-dir	The path in the KV store that is used to store the replication statuses. The default value is "service/consul-replicate/statuses".

If you make a change on the PHL side it should come over, but if you make a change on the ATL side it won't detect it because it is looking at its saved state about what has been replicated from PHL, not doing a diff. If you remove the state in the key above it should replicate everything again.

**Comment by ssenaria** [comment]
So deleting a key or modifying a value on the ATL side should resume correct? It's not ...

**Comment by slackpad** [comment]
If I understand correctly ATL is the side that's pulling from PHL - deleting or modifying a value in ATL won't cause it to resume. ATL is trying to make a copy of PHL by watching for changes in PHL, it doesn't monitor ATL for local changes.

**Comment by ssenaria** [comment]
Ah...OK.

Let's say I have a key called `mykey1` and `mykey2` that were synced between PHL and ATL. If I delete `mykey2` on the ATL side, you're saying PHL won't resync the keys again?

If so, is there a way to force it? I suppose one wouldn't just go into ATL and randomly delete keys, but something happened (I don't recall) on the ATL side that caused me to look into the syncing "issue."

**Comment by slackpad** [comment]
Yes - to force it you can shut down consul-replicate and then delete the `service/consul-replicate/statuses` key it was using to keep track of state. This will cause consul-replicate to start over and replicate everything fresh again.
