### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by joehillen** [hashicorp/consul-replicate#61]
Would you all be willing to make a new release?

I'd like the latest `-once` and `-exclude` fixes, ~~and I can't seem to build from source.~~

~~When I run `make`, I get this hot mess:~~

**Comment by ntnn** [comment]
Currently you can't build packages outside of the ``GOPATH``.
https://golang.org/doc/install

**Comment by joehillen** [comment]
Ah, I needed to move the repo to `~/src/go/src/github.com/hashicorp/consul-replicate`. Thank you @ntnn 

Still a release would be nice.

**Comment by sethvargo** [comment]
v0.3.0 is out
