### ISSUE TITLE
Replication is broken

### ISSUE THREAD

**Issue by sitano** [hashicorp/consul-replicate#67]
1) Config.Prefix.DataCenter in release 0.3.0 stands for nothing
2) Prefix.Source = "path@datacenter" results into wrong keys being replicated:

i.e.

key -> key@dckey
a/b -> a/b@dca/b
...

**Comment by sethvargo** [comment]
Hi there,

Thank you for opening an issue. This was reported in https://github.com/hashicorp/consul-replicate/issues/66 and has already been fixed on master. Thanks!

**Comment by sitano** [comment]
@sethvargo just tested it, it did not fix. it's not working. I am still getting those key@dckey keys updates even with right config. 
```
prefix {
source = "key"
datacenter = "dc"
}
```
