### ISSUE TITLE
Style: redundant code

### ISSUE THREAD

**Issue by sitano** [hashicorp/consul-replicate#68]
All such pieces of code which trying to precreate 0 len 1 cap array right before append are redundant.

```
if c.Prefixes == nil {
    c.Prefixes = make([]*Prefix, 0, 1)
}
c.Prefixes = append(c.Prefixes, p)
```

it should be

```
c.Prefixes = append(c.Prefixes, p)
```

**Comment by sethvargo** [comment]
Hi @sitano 

This is something we will fix over time. Thank you for reporting!
