### ISSUE TITLE
v0.3.0 release is broken

### ISSUE THREAD

**Issue by lewispeckover** [hashicorp/consul-replicate#71]
It's not possible to build that tag. It appears to point to the wrong commit; it points to f9fb20a when it looks like it should be 96ce9f0.

**Comment by sethvargo** [comment]
Hi @lewispeckover 

Thank you for opening an issue. I'm not sure how that happened, and I'm sorry about that. It's generally a very bad practice to overwrite a tag, but I've just released v0.3.1 which includes two important bug fixes, and I verified you are able to build directly from it.

Super sorry about that!

**Comment by gobins** [comment]
Hi @sethvargo , just trying to confirm if v0.3.1 released? I could see that there is a tag and there are binaries are there in the release page but the changelog still says v0.3.1.dev here:
https://github.com/hashicorp/consul-replicate/blob/v0.3.1/CHANGELOG.md#v031dev-january-28-2017
