### ISSUE TITLE
Can't install consul-replicate from source

### ISSUE THREAD

**Issue by wemmsi** [hashicorp/consul-replicate#72]
Hi everyone,

if I try to install consul-replicate from source I got some errors:
ubuntu@consul-server01:/usr/lib/go-1.6/src/github.com/hashicorp/consul-replicate$ make
==> Building github.com/hashicorp/consul-replicate (locally)...
-->         darwin/386: github.com/hashicorp/consul-replicate
 github.com/hashicorp/consul-replicate/vendor/github.com/hashicorp/vault/api
/usr/lib/go-1.6/src/github.com/hashicorp/consul-replicate/vendor/github.com/hashicorp/vault/api/client.go:260: undefined: http.ErrUseLastResponse
Makefile:67: recipe for target 'bin-local' failed
make: *** [bin-local] Error 2

I 'm using Ubuntu 16.04 and go version 1.6.

Kind regards

**Comment by sethvargo** [comment]
Hi there,

The minimum required go version is 1.7. I've updated this in the README. If you use the docker builder, you'll get the proper version each time (`make dev`).

You can also download a pre-compiled binary at https://releases.hashicorp.com/
