### ISSUE TITLE
Only replicate changes, don't re-scan the whole KV

### ISSUE THREAD

**Issue by mrwulf** [hashicorp/consul-replicate#77]
Replicating using full-scans seems inefficient. According to the watch documentation (https://www.consul.io/docs/agent/watches.html) it sounds like one can create a watch and only replicate changes. In reality consul-replicate does a full scan of the source and then chooses what to replicate. This ends up clobbering any "extra" keys that have been added to the destination. It also ends up having to traverse the whole tree.

Can consul-replicate be tweaked to only replicate changes (create/update/delete) instead of traversing the whole source tree? Is there a better way to do this?

**Comment by ntnn** [comment]
Hooks inside consul would be ideal.

Trigger: creation/update
Payload:
```json
{
    "path":"/some/path",
    "value":"val"
}
```

Trigger: deletion
Payload:
```json
{
    "path":"/some/path"
}
```

consul-replicate could then register hooks for the respective targets.

**Comment by sethvargo** [comment]
We create the same number of watches on the KV that watches do internally. They functionally map to the same blocking queries. Additionally, we have to traverse to handle client-side excluded keys.

It's important to note that we aren't "traversing" the KV on the server. We get the entire KV as one response and do client-side filtering.

If you don't need excludes, you can build your own mini consul-replicate using watches, but you won't be able to exclude keys and you'll have to handle state in the event of partial replication or failure (i.e. how do find out what data was missed in the event of a partial outage).
