### ISSUE TITLE
How about the Service data replicate arocss DCs?

### ISSUE THREAD

**Issue by hehailong5** [hashicorp/consul-replicate#79]

**Comment by sethvargo** [comment]
Hi there,

Thank you for opening an issue. Unfortunately I'm not sure what you're asking. Could you please elaborate a bit more, perhaps with example output or a more descriptive text? Thanks!

**Comment by hehailong5** [comment]
Hi,

I'm concerned with the catalog service entries, can that be replicated across DCs using this tool?

**Comment by sethvargo** [comment]
Hi @hehailong5 

No, this tool only replicates key-value data across multiple data centers. It is not possible to replicate services across DCs. You can read more about Consul's multi-datacenter DC architecture here: https://www.consul.io/docs/internals/architecture.html.

You can use the consul snapshot command if you're looking for more of a backup strategy: https://www.consul.io/docs/commands/snapshot.html.
