### ISSUE TITLE
consul-replicate overwrites keys with the same prefix in the destination data center as the source

### ISSUE THREAD

**Issue by mssawant** [hashicorp/consul-replicate#98]
Existing keys in data center 1 with prefix proc/
```
consul kv get -datacenter=dc1 -recurse proc/
proc/1:online
proc/2:online
proc/3:failed

 consul kv get -datacenter=dc2 -recurse proc/
proc/3:failed
proc/4:online
```
Try replicating all the keys from data center 2 with the same prefix, proc/.
```
 ./consul-replicate -prefix "proc/@dc2" -once
```
So instead of appending to the existing keys, consul-replicate overwrites all the keys with the prefix proc/ in dc1 with the ones from dc2.
```
[root@ssc-vm-1623:520478] consul kv get -datacenter=dc1 -recurse proc/
proc/3:failed
proc/4:online
```

**Comment by blake** [comment]
Hi @mssawant, this is expected behavior. Consul replicate will synchronize the specified KV path from the source to the destination. Keys which exist at the destination but do not exist at the source will be deleted (similar to rsync's `--delete` flag).

You can exclude specific keys/prefixes from replication (and hence deletion on the dst) by using the `-exclude` flag at the CLI, or `exclude` key in the configuration file.

**Comment by mssawant** [comment]
Okay, I am getting what I want if I specify the absolute key name in exclude but not if I specify just the prefix,
```
consul kv get -datacenter=dc1 -recurse proc/
proc/1:online
proc/2:online

consul kv get -datacenter=dc2 -recurse proc/
proc/3:online
proc/4:
```
```
./consul-replicate -exclude="proc/1" -exclude="proc/2" -prefix "proc/@dc2" -once
consul kv get -recurse proc/
proc/1:online
proc/2:online
proc/3:online
proc/4:online

consul kv delete proc/3
Success! Deleted key: proc/3
consul kv delete proc/4
Success! Deleted key: proc/4
consul kv get -recurse proc/
proc/1:online
proc/2:online
./consul-replicate -exclude="proc/" -prefix "proc/@dc2" -once
consul kv get -recurse proc/
proc/1:online
proc/2:online
```
But I think the behavior's as expected. Just that I have a hybrid use case where I divide my cluster in multiple datacenters and need certain level of redundancy between the data centers maintaining their local keys.
Good that there's a workaround, thanks @blake.

**Comment by blake** [comment]
I'm glad you have a workable solution. Do you mind if I close this issue?
